package br.com.alura.comex.relatorios;

public enum CategoriaRelatorio {
    RELATORIO_SINTETICO,
    RELATORIO_CLIENTES_FIEIS,
    RELATORIO_VENDAS_POR_CATEGORIA,
    RELATORIO_PRODUTOS_MAIS_VENDIDOS,
    RELATORIO_PRODUTOS_MAIS_CAROS,
    RELATORIO_CLIENTES_MAIS_LUCRATIVOS
}
